In [84]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras

In [85]:
data_ours=pd.read_csv("data_ours.csv")

In [86]:
data_ours.head()

,Unnamed: 0,phase,vacancy,chiral_orientation,Strain_rate,Strain,Stress,molecular_mass,crack_length,temperature,% ionic character
0,0,h,1v2s,Armchair,10000000000,0.00035,0.054708,115.08,no,300,16.752729
1,1,h,1v2s,Armchair,10000000000,0.00095,0.124270,115.08,no,300,16.752729
2,2,h,1v2s,Armchair,10000000000,0.00155,0.192165,115.08,no,300,16.752729
3,3,h,1v2s,Armchair,10000000000,0.00215,0.251728,115.08,no,300,16.752729
4,4,h,1v2s,Armchair,10000000000,0.00275,0.355276,115.08,no,300,16.752729

In [87]:
data_bang=pd.read_csv("data_bang.csv")

In [88]:
data_bang.head()

,Unnamed: 0,Strain,Direction,Crack length,Temperature,Stress,phase,molecular_mass,vacancy,Strain_rate,%ionic character
0,0,0.000,Armchair,0,100,0.000000,h,160.07,no,1000000000,5.343447
1,1,0.001,Armchair,0,100,0.098407,h,160.07,no,1000000000,5.343447
2,2,0.002,Armchair,0,100,0.191496,h,160.07,no,1000000000,5.343447
3,3,0.003,Armchair,0,100,0.285939,h,160.07,no,1000000000,5.343447
4,4,0.004,Armchair,0,100,0.394138,h,160.07,no,1000000000,5.343447

In [89]:
column=["phase","vacancy","crack_length","molecular_mass","chiral_orientation","% ionic character","strain_rate","temperature","strain","stress"]

In [90]:
data_ours.head()

,Unnamed: 0,phase,vacancy,chiral_orientation,Strain_rate,Strain,Stress,molecular_mass,crack_length,temperature,% ionic character
0,0,h,1v2s,Armchair,10000000000,0.00035,0.054708,115.08,no,300,16.752729
1,1,h,1v2s,Armchair,10000000000,0.00095,0.124270,115.08,no,300,16.752729
2,2,h,1v2s,Armchair,10000000000,0.00155,0.192165,115.08,no,300,16.752729
3,3,h,1v2s,Armchair,10000000000,0.00215,0.251728,115.08,no,300,16.752729
4,4,h,1v2s,Armchair,10000000000,0.00275,0.355276,115.08,no,300,16.752729

In [91]:
data_ours.rename(columns={"phase":column[0],
                      "vacancy":column[1],
                      "crack_length":column[2],
                      "molecular_mass":column[3],
                      "chiral_orientation":column[4],
                      "% ionic character":column[5],
                      "Strain_rate":column[6],
                      "temperature":column[7],
                      "Strain":column[8],
                      "Stress":column[9]
                    },inplace=True)

In [95]:
data_bang.head()

,Unnamed: 0,Strain,Direction,Crack length,Temperature,Stress,phase,molecular_mass,vacancy,Strain_rate,%ionic character
0,0,0.000,Armchair,0,100,0.000000,h,160.07,no,1000000000,5.343447
1,1,0.001,Armchair,0,100,0.098407,h,160.07,no,1000000000,5.343447
2,2,0.002,Armchair,0,100,0.191496,h,160.07,no,1000000000,5.343447
3,3,0.003,Armchair,0,100,0.285939,h,160.07,no,1000000000,5.343447
4,4,0.004,Armchair,0,100,0.394138,h,160.07,no,1000000000,5.343447

In [96]:
data_bang.rename(columns={"phase":column[0],
                      "vacancy":column[1],
                      "Crack length":column[2],
                      "molecular_mass":column[3],
                      "Direction":column[4],
                      "%ionic character":column[5],
                      "Strain_rate":column[6],
                      "Temperature":column[7],
                      "Strain":column[8],
                      "Stress":column[9]
                    },inplace=True)

In [97]:
data_bang.head()

,Unnamed: 0,strain,chiral_orientation,crack_length,temperature,stress,phase,molecular_mass,vacancy,strain_rate,% ionic character
0,0,0.000,Armchair,0,100,0.000000,h,160.07,no,1000000000,5.343447
1,1,0.001,Armchair,0,100,0.098407,h,160.07,no,1000000000,5.343447
2,2,0.002,Armchair,0,100,0.191496,h,160.07,no,1000000000,5.343447
3,3,0.003,Armchair,0,100,0.285939,h,160.07,no,1000000000,5.343447
4,4,0.004,Armchair,0,100,0.394138,h,160.07,no,1000000000,5.343447

In [ ]:
temp1.rename(columns={"phase":column[0],
                      "vacancy":column[1],
                      "Crack length":column[2],
                      "Molecular_mass":column[3],
                      "Direction":column[4],
                      "% ionic character":column[5],
                      "Strain_rate":column[6],
                      "Temperature":column[7],
                      "Strain":column[8],
                      "Stress":column[9]
                    },inplace=True)

In [98]:
data_ours.to_csv("data_ours_final.csv")

In [ ]:
data_bang